// Code generated by MockGen. DO NOT EDIT.
// Source: command_bus.go

// Package mock_cqrs is a generated GoMock package.
package mock_cqrs

import (
	context "context"
	reflect "reflect"

	cqrs "github.com/vulpes-ferrilata/cqrs"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandBus is a mock of CommandBus interface.
type MockCommandBus struct {
	ctrl     *gomock.Controller
	recorder *MockCommandBusMockRecorder
}

// MockCommandBusMockRecorder is the mock recorder for MockCommandBus.
type MockCommandBusMockRecorder struct {
	mock *MockCommandBus
}

// NewMockCommandBus creates a new mock instance.
func NewMockCommandBus(ctrl *gomock.Controller) *MockCommandBus {
	mock := &MockCommandBus{ctrl: ctrl}
	mock.recorder = &MockCommandBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandBus) EXPECT() *MockCommandBusMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCommandBus) Execute(ctx context.Context, command interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandBusMockRecorder) Execute(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommandBus)(nil).Execute), ctx, command)
}

// Register mocks base method.
func (m *MockCommandBus) Register(handler interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockCommandBusMockRecorder) Register(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockCommandBus)(nil).Register), handler)
}

// Use mocks base method.
func (m *MockCommandBus) Use(middlewares ...cqrs.CommandMiddlewareFunc) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range middlewares {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Use", varargs...)
}

// Use indicates an expected call of Use.
func (mr *MockCommandBusMockRecorder) Use(middlewares ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockCommandBus)(nil).Use), middlewares...)
}
