// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go

// Package mock_validator is a generated GoMock package.
package mock_validator

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockValidate is a mock of Validate interface.
type MockValidate struct {
	ctrl     *gomock.Controller
	recorder *MockValidateMockRecorder
}

// MockValidateMockRecorder is the mock recorder for MockValidate.
type MockValidateMockRecorder struct {
	mock *MockValidate
}

// NewMockValidate creates a new mock instance.
func NewMockValidate(ctrl *gomock.Controller) *MockValidate {
	mock := &MockValidate{ctrl: ctrl}
	mock.recorder = &MockValidateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidate) EXPECT() *MockValidateMockRecorder {
	return m.recorder
}

// StructCtx mocks base method.
func (m *MockValidate) StructCtx(ctx context.Context, s interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StructCtx", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// StructCtx indicates an expected call of StructCtx.
func (mr *MockValidateMockRecorder) StructCtx(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StructCtx", reflect.TypeOf((*MockValidate)(nil).StructCtx), ctx, s)
}
